export default {
  getters: {
    ITEMS: 'users/items',
    SELECTED: 'users/selected',
    SELECTED_IDS: 'users/selectedIds',
    QUERY_PARAMS: 'users/queryParams',
    LOADING: 'users/isLoading',
    HAS_MORE: 'users/hasMore',
  },
  mutations: {
    SET_ITEMS: 'users/setItems',
    SET_SELECTED: 'users/setSelected',
    SET_PARAM: 'users/setParam',
    SET_HAS_MORE: 'users/setHasMore',
    SET_LOADING: 'users/setLoading',
    UPDATE_ITEM: 'users/updateItem',
    ADD_ROLE: 'users/addRole',
    ADD_ITEM: 'users/addItem',
    EXCLUDE_FROM_FETCH: 'users/exclude',
    REMOVE_FROM_EXCLUDE: 'roles/removeFromExclude',
    REMOVE_ITEMS: 'users/removeItems',
    REMOVE_ROLE: 'users/removeRole',
    CLEAR_ITEMS: 'users/clearItems',
  },
  actions: {
    FETCH: 'users/fetchItems',
    RESET_CURSORS: 'users/resetCursors',
    RESET_FILTERS: 'users/resetFilters',
    ADD_ROLE: 'users/addRoleToUser',
    REMOVE_ITEMS: 'users/removeItems',
    REMOVE_ROLE: 'users/removeRoleFromUser',
    DISABLE_USER: 'users/disableUser',
    ADD_ITEM: 'users/addItem',
    UPDATE_ITEM: 'users/updateItem',
    CLEAR_ITEMS: 'users/clearItems',
  },
};
