export default {
  getters: {
    ITEMS: 'rosters/items',
    SELECTED: 'rosters/selected',
    SELECTED_IDS: 'rosters/selectedIds',
    QUERY_PARAMS: 'rosters/queryParams',
    HAS_MORE: 'rosters/hasMore',
    LOADING: 'rosters/loading',
  },
  mutations: {
    SET_ITEMS: 'rosters/setItems',
    SET_SELECTED: 'rosters/setSelected',
    SET_PARAM: 'rosters/setParam',
    SET_HAS_MORE: 'rosters/setHasMore',
    SET_LOADING: 'rosters/setLoading',
    ADD_ITEM: 'rosters/addItem',
    UPDATE_ITEM: 'rosters/updateRoster',
    REMOVE_ITEMS: 'rosters/removeRoster',
    CLEAR_ITEMS: 'rosters/clearItems',
    EXCLUDE_FROM_FETCH: 'rosters/exclude',
    REMOVE_FROM_EXCLUDE: 'rosters/removeFromExclude',
  },
  actions: {
    FETCH: 'rosters/fetchRosters',
    RESET_CURSORS: 'rosters/resetCursors',
    ADD_ITEM: 'rosters/addRoster',
    UPDATE_ITEM: 'rosters/updateRosters',
    REMOVE_ITEMS: 'rosters/removeItems',
    CLEAR_ITEMS: 'rosters/clearItems',
  },
};
